spring.application.name=hr-worker

#DB initializr
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true

#Config server
server.port=8001
eureka.clent.service-url.defaultZone=http://localhost:8761/eureka

# Database configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console