spring.application.name=hr-api-gateway

server.port=8765
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.cloud.gateway.routes[0].id=worker-route
spring.cloud.gateway.routes[0].uri=lb://hr-worker
spring.cloud.gateway.routes[0].predicates[0]=Path=/hr-worker/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/hr-worker/(?<segment>.*), /${segment}

spring.cloud.gateway.routes[1].id=payroll-route
spring.cloud.gateway.routes[1].uri=lb://hrpayroll
spring.cloud.gateway.routes[1].predicates[0]=Path=/hrpayroll/**